import pandas as pd
import matplotlib.pyplot as plt

from crypto_trader.backtester.data import get_historical_prices
from crypto_trader.backtester.backtester import run_backtest
from crypto_trader.backtester.strategies import moving_average_crossover

# Set the backtesting parameters
symbol = "BTC/USDT"

# Retrieve historical price data using the get_historical_prices function
prices = get_historical_prices(
    symbol=symbol,
)

print(prices.head())

# # Run the backtest using the moving_average_crossover strategy function
# results = run_backtest(prices, strategy=moving_average_crossover)

# # Plot the historical prices on a line chart
# plt.plot(prices["close"])

# # Highlight the buy and sell signals generated by the strategy
# buy_signals = results[results["signal"] == 1].index
# sell_signals = results[results["signal"] == -1].index
# plt.plot(
#     buy_signals,
#     prices.loc[buy_signals, "close"],
#     "^",
#     markersize=10,
#     color="green",
#     label="Buy Signal",
# )
# plt.plot(
#     sell_signals,
#     prices.loc[sell_signals, "close"],
#     "v",
#     markersize=10,
#     color="red",
#     label="Sell Signal",
# )

# # Add a legend and axis labels
# plt.legend(loc="upper left")
# plt.xlabel("Date")
# plt.ylabel("Price")

# # Show the plot
# plt.show()
